# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'system.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 622)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 120, 471))
        self.widget.setObjectName("widget")
        self.layoutWidget = QtWidgets.QWidget(self.widget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 100, 120))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.commodity_btn = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.commodity_btn.setFont(font)
        self.commodity_btn.setObjectName("commodity_btn")
        self.gridLayout.addWidget(self.commodity_btn, 0, 0, 1, 1)
        self.employee_btn = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.employee_btn.setFont(font)
        self.employee_btn.setObjectName("employee_btn")
        self.gridLayout.addWidget(self.employee_btn, 1, 0, 1, 1)
        self.receipt_btn = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.receipt_btn.setFont(font)
        self.receipt_btn.setObjectName("receipt_btn")
        self.gridLayout.addWidget(self.receipt_btn, 2, 0, 1, 1)
        self.detail_btn = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.detail_btn.setFont(font)
        self.detail_btn.setObjectName("detail_btn")
        self.gridLayout.addWidget(self.detail_btn, 3, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(150, 60, 631, 491))
        self.widget_2.setObjectName("widget_2")
        self.tableView = QtWidgets.QTableView(self.widget_2)
        self.tableView.setGeometry(QtCore.QRect(10, 10, 601, 431))
        self.tableView.setObjectName("tableView")
        self.next_btn = QtWidgets.QPushButton(self.widget_2)
        self.next_btn.setGeometry(QtCore.QRect(530, 450, 75, 23))
        self.next_btn.setObjectName("next_btn")
        self.pre_btn = QtWidgets.QPushButton(self.widget_2)
        self.pre_btn.setGeometry(QtCore.QRect(10, 450, 75, 23))
        self.pre_btn.setObjectName("pre_btn")
        self.keyword = QtWidgets.QLineEdit(self.centralwidget)
        self.keyword.setGeometry(QtCore.QRect(161, 22, 133, 20))
        self.keyword.setObjectName("keyword")
        self.feature = QtWidgets.QComboBox(self.centralwidget)
        self.feature.setGeometry(QtCore.QRect(297, 22, 121, 20))
        self.feature.setObjectName("feature")
        self.search_btn = QtWidgets.QPushButton(self.centralwidget)
        self.search_btn.setGeometry(QtCore.QRect(424, 21, 75, 23))
        self.search_btn.setObjectName("search_btn")
        self.update_btn = QtWidgets.QPushButton(self.centralwidget)
        self.update_btn.setGeometry(QtCore.QRect(505, 21, 75, 23))
        self.update_btn.setObjectName("update_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.commodity = QtWidgets.QMenu(self.menubar)
        self.commodity.setObjectName("commodity")
        self.employee = QtWidgets.QMenu(self.menubar)
        self.employee.setObjectName("employee")
        self.receipt = QtWidgets.QMenu(self.menubar)
        self.receipt.setObjectName("receipt")
        self.detail = QtWidgets.QMenu(self.menubar)
        self.detail.setObjectName("detail")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionnew = QtWidgets.QAction(MainWindow)
        self.actionnew.setObjectName("actionnew")
        self.actiondelete = QtWidgets.QAction(MainWindow)
        self.actiondelete.setObjectName("actiondelete")
        self.actionnew_2 = QtWidgets.QAction(MainWindow)
        self.actionnew_2.setObjectName("actionnew_2")
        self.actiondelete_2 = QtWidgets.QAction(MainWindow)
        self.actiondelete_2.setObjectName("actiondelete_2")
        self.actionnew_3 = QtWidgets.QAction(MainWindow)
        self.actionnew_3.setObjectName("actionnew_3")
        self.actiondelete_3 = QtWidgets.QAction(MainWindow)
        self.actiondelete_3.setObjectName("actiondelete_3")
        self.actionnew_4 = QtWidgets.QAction(MainWindow)
        self.actionnew_4.setObjectName("actionnew_4")
        self.actiondelete_4 = QtWidgets.QAction(MainWindow)
        self.actiondelete_4.setObjectName("actiondelete_4")
        self.commodity.addAction(self.actionnew)
        self.commodity.addAction(self.actiondelete)
        self.employee.addAction(self.actionnew_2)
        self.employee.addAction(self.actiondelete_2)
        self.receipt.addAction(self.actionnew_3)
        self.receipt.addAction(self.actiondelete_3)
        self.detail.addAction(self.actionnew_4)
        self.detail.addAction(self.actiondelete_4)
        self.menubar.addAction(self.commodity.menuAction())
        self.menubar.addAction(self.employee.menuAction())
        self.menubar.addAction(self.receipt.menuAction())
        self.menubar.addAction(self.detail.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "超市管理主界面"))
        self.commodity_btn.setText(_translate("MainWindow", "商品表"))
        self.employee_btn.setText(_translate("MainWindow", "职员表"))
        self.receipt_btn.setText(_translate("MainWindow", "收据单表"))
        self.detail_btn.setText(_translate("MainWindow", "收据明细表"))
        self.next_btn.setText(_translate("MainWindow", "下一页"))
        self.pre_btn.setText(_translate("MainWindow", "上一页"))
        self.search_btn.setText(_translate("MainWindow", "搜索"))
        self.update_btn.setText(_translate("MainWindow", "刷新"))
        self.commodity.setTitle(_translate("MainWindow", "商品"))
        self.employee.setTitle(_translate("MainWindow", "职员"))
        self.receipt.setTitle(_translate("MainWindow", "收据"))
        self.detail.setTitle(_translate("MainWindow", "收据细节"))
        self.actionnew.setText(_translate("MainWindow", "new"))
        self.actiondelete.setText(_translate("MainWindow", "delete"))
        self.actionnew_2.setText(_translate("MainWindow", "new"))
        self.actiondelete_2.setText(_translate("MainWindow", "delete"))
        self.actionnew_3.setText(_translate("MainWindow", "new"))
        self.actiondelete_3.setText(_translate("MainWindow", "delete"))
        self.actionnew_4.setText(_translate("MainWindow", "new"))
        self.actiondelete_4.setText(_translate("MainWindow", "delete"))


