# Generated by Django 3.1.5 on 2021-02-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactApp', '0002_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='birth',
            field=models.DateField(default='2021-02-01', max_length=20, verbose_name='出生日期'),
        ),
    ]
