# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'final.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Final(object):
    def setupUi(self, Final):
        Final.setObjectName("Final")
        Final.resize(682, 443)
        self.tabWidget = QtWidgets.QTabWidget(Final)
        self.tabWidget.setGeometry(QtCore.QRect(10, 70, 311, 341))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.car1 = QtWidgets.QPushButton(self.tab)
        self.car1.setGeometry(QtCore.QRect(20, 20, 75, 75))
        self.car1.setToolTip("")
        self.car1.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pic/car.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.car1.setIcon(icon)
        self.car1.setIconSize(QtCore.QSize(60, 60))
        self.car1.setObjectName("car1")
        self.car3 = QtWidgets.QPushButton(self.tab)
        self.car3.setGeometry(QtCore.QRect(200, 20, 75, 75))
        self.car3.setText("")
        self.car3.setIcon(icon)
        self.car3.setIconSize(QtCore.QSize(60, 60))
        self.car3.setObjectName("car3")
        self.car4 = QtWidgets.QPushButton(self.tab)
        self.car4.setGeometry(QtCore.QRect(20, 110, 75, 75))
        self.car4.setText("")
        self.car4.setIcon(icon)
        self.car4.setIconSize(QtCore.QSize(60, 60))
        self.car4.setObjectName("car4")
        self.car8 = QtWidgets.QPushButton(self.tab)
        self.car8.setGeometry(QtCore.QRect(110, 200, 75, 75))
        self.car8.setText("")
        self.car8.setIcon(icon)
        self.car8.setIconSize(QtCore.QSize(60, 60))
        self.car8.setObjectName("car8")
        self.car7 = QtWidgets.QPushButton(self.tab)
        self.car7.setGeometry(QtCore.QRect(20, 200, 75, 75))
        self.car7.setText("")
        self.car7.setIcon(icon)
        self.car7.setIconSize(QtCore.QSize(60, 60))
        self.car7.setObjectName("car7")
        self.car9 = QtWidgets.QPushButton(self.tab)
        self.car9.setGeometry(QtCore.QRect(200, 200, 75, 75))
        self.car9.setText("")
        self.car9.setIcon(icon)
        self.car9.setIconSize(QtCore.QSize(60, 60))
        self.car9.setObjectName("car9")
        self.car6 = QtWidgets.QPushButton(self.tab)
        self.car6.setGeometry(QtCore.QRect(200, 110, 75, 75))
        self.car6.setText("")
        self.car6.setIcon(icon)
        self.car6.setIconSize(QtCore.QSize(60, 60))
        self.car6.setObjectName("car6")
        self.car2 = QtWidgets.QPushButton(self.tab)
        self.car2.setGeometry(QtCore.QRect(110, 20, 75, 75))
        self.car2.setText("")
        self.car2.setIcon(icon)
        self.car2.setIconSize(QtCore.QSize(60, 60))
        self.car2.setObjectName("car2")
        self.car5 = QtWidgets.QPushButton(self.tab)
        self.car5.setGeometry(QtCore.QRect(110, 110, 75, 75))
        self.car5.setText("")
        self.car5.setIcon(icon)
        self.car5.setIconSize(QtCore.QSize(60, 60))
        self.car5.setObjectName("car5")
        self.tabWidget.addTab(self.tab, "")
        self.tabWidget_2 = QtWidgets.QTabWidget(Final)
        self.tabWidget_2.setGeometry(QtCore.QRect(330, 90, 324, 316))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 2, 1, 2)
        self.Class = QtWidgets.QComboBox(self.tab_2)
        self.Class.setObjectName("Class")
        self.gridLayout.addWidget(self.Class, 0, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 2, 1, 1)
        self.location = QtWidgets.QComboBox(self.tab_2)
        self.location.setObjectName("location")
        self.gridLayout.addWidget(self.location, 1, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 2, 1, 1)
        self.hum = QtWidgets.QLineEdit(self.tab_2)
        self.hum.setObjectName("hum")
        self.gridLayout.addWidget(self.hum, 2, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 2, 1, 1)
        self.temp = QtWidgets.QLineEdit(self.tab_2)
        self.temp.setObjectName("temp")
        self.gridLayout.addWidget(self.temp, 3, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 2, 1, 1)
        self.light = QtWidgets.QComboBox(self.tab_2)
        self.light.setObjectName("light")
        self.gridLayout.addWidget(self.light, 4, 4, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 2, 1, 1)
        self.Click = QtWidgets.QComboBox(self.tab_2)
        self.Click.setObjectName("Click")
        self.gridLayout.addWidget(self.Click, 5, 4, 1, 1)
        self.cancel = QtWidgets.QPushButton(self.tab_2)
        self.cancel.setObjectName("cancel")
        self.gridLayout.addWidget(self.cancel, 6, 4, 1, 1)
        self.update = QtWidgets.QPushButton(self.tab_2)
        self.update.setObjectName("update")
        self.gridLayout.addWidget(self.update, 6, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(":/pic/light.jpg"))
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap(":/pic/temp.jpg"))
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 3, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap(":/pic/hum.jpg"))
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap(":/pic/click.jpg"))
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 5, 1, 1, 1)
        self.tabWidget_2.addTab(self.tab_2, "")
        self.MyMessage = QtWidgets.QPushButton(Final)
        self.MyMessage.setGeometry(QtCore.QRect(560, 50, 75, 23))
        self.MyMessage.setObjectName("MyMessage")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(Final)
        self.dateTimeEdit.setGeometry(QtCore.QRect(350, 50, 194, 22))
        self.dateTimeEdit.setObjectName("dateTimeEdit")

        self.retranslateUi(Final)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Final)

    def retranslateUi(self, Final):
        _translate = QtCore.QCoreApplication.translate
        Final.setWindowTitle(_translate("Final", "实时界面"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Final", "物品信息"))
        self.label.setText(_translate("Final", "物品类别："))
        self.label_2.setText(_translate("Final", "位置："))
        self.label_4.setText(_translate("Final", "湿度："))
        self.label_3.setText(_translate("Final", "温度："))
        self.label_5.setText(_translate("Final", "光照："))
        self.label_6.setText(_translate("Final", "碰撞："))
        self.cancel.setText(_translate("Final", "取消"))
        self.update.setText(_translate("Final", "更改"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("Final", "实时信息"))
        self.MyMessage.setText(_translate("Final", "我的信息"))
        self.dateTimeEdit.setDisplayFormat(_translate("Final", "yyyy-MM-dd HH:mm:ss"))


import source.apprcc_rc
