# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Mine.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Mine(object):
    def setupUi(self, Mine):
        Mine.setObjectName("Mine")
        Mine.resize(445, 337)
        self.gridLayout_2 = QtWidgets.QGridLayout(Mine)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_8 = QtWidgets.QLabel(Mine)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 6, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(Mine)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.msg6 = QtWidgets.QLineEdit(Mine)
        self.msg6.setPlaceholderText("")
        self.msg6.setObjectName("msg6")
        self.gridLayout.addWidget(self.msg6, 5, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(Mine)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 0, 1, 1)
        self.msg1 = QtWidgets.QLineEdit(Mine)
        self.msg1.setObjectName("msg1")
        self.gridLayout.addWidget(self.msg1, 0, 2, 1, 1)
        self.msg7 = QtWidgets.QTextEdit(Mine)
        self.msg7.setPlaceholderText("")
        self.msg7.setObjectName("msg7")
        self.gridLayout.addWidget(self.msg7, 6, 2, 1, 1)
        self.msg2 = QtWidgets.QLineEdit(Mine)
        self.msg2.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.msg2.setObjectName("msg2")
        self.gridLayout.addWidget(self.msg2, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(Mine)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.msg3 = QtWidgets.QLineEdit(Mine)
        self.msg3.setObjectName("msg3")
        self.gridLayout.addWidget(self.msg3, 2, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(Mine)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.msg5 = QtWidgets.QLineEdit(Mine)
        self.msg5.setInputMask("")
        self.msg5.setPlaceholderText("")
        self.msg5.setObjectName("msg5")
        self.gridLayout.addWidget(self.msg5, 4, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(Mine)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(Mine)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.msg4 = QtWidgets.QComboBox(Mine)
        self.msg4.setObjectName("msg4")
        self.gridLayout.addWidget(self.msg4, 3, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Sure = QtWidgets.QPushButton(Mine)
        self.Sure.setObjectName("Sure")
        self.horizontalLayout.addWidget(self.Sure)
        self.fresh = QtWidgets.QPushButton(Mine)
        self.fresh.setObjectName("fresh")
        self.horizontalLayout.addWidget(self.fresh)
        self.exit = QtWidgets.QPushButton(Mine)
        self.exit.setObjectName("exit")
        self.horizontalLayout.addWidget(self.exit)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)

        self.retranslateUi(Mine)
        QtCore.QMetaObject.connectSlotsByName(Mine)
        Mine.setTabOrder(self.msg1, self.msg2)
        Mine.setTabOrder(self.msg2, self.msg3)
        Mine.setTabOrder(self.msg3, self.msg5)
        Mine.setTabOrder(self.msg5, self.msg6)
        Mine.setTabOrder(self.msg6, self.msg7)
        Mine.setTabOrder(self.msg7, self.Sure)
        Mine.setTabOrder(self.Sure, self.fresh)
        Mine.setTabOrder(self.fresh, self.exit)

    def retranslateUi(self, Mine):
        _translate = QtCore.QCoreApplication.translate
        Mine.setWindowTitle(_translate("Mine", "我的信息"))
        self.label_8.setText(_translate("Mine", "地址"))
        self.label_4.setText(_translate("Mine", "手机号"))
        self.label_7.setText(_translate("Mine", "邮箱"))
        self.msg1.setPlaceholderText(_translate("Mine", "不能为空"))
        self.msg2.setPlaceholderText(_translate("Mine", "不能为空"))
        self.label_3.setText(_translate("Mine", "密码"))
        self.msg3.setPlaceholderText(_translate("Mine", "不能为空"))
        self.label_5.setText(_translate("Mine", "性别"))
        self.label_2.setText(_translate("Mine", "用户名"))
        self.label_6.setText(_translate("Mine", "真实姓名"))
        self.Sure.setText(_translate("Mine", "确认修改"))
        self.fresh.setText(_translate("Mine", "初始化"))
        self.exit.setText(_translate("Mine", "退出"))


