# Generated by Django 3.1.5 on 2021-03-09 08:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='留言用户')),
                ('email', models.CharField(max_length=50, verbose_name='邮箱地址')),
                ('content', models.CharField(max_length=500, verbose_name='留言内容')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '博客留言',
                'verbose_name_plural': '博客留言',
            },
        ),
    ]
