# Generated by Django 3.1.5 on 2021-03-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interflowApp', '0003_auto_20210311_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='邮箱地址'),
        ),
    ]
