# Generated by Django 3.1.5 on 2021-03-14 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interflowApp', '0004_auto_20210311_1650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'verbose_name': '访客留言', 'verbose_name_plural': '访客留言'},
        ),
        migrations.AddField(
            model_name='board',
            name='file',
            field=models.FileField(default='', upload_to='files', verbose_name='上传文件'),
        ),
        migrations.AlterField(
            model_name='board',
            name='content',
            field=models.TextField(max_length=500, verbose_name='留言内容'),
        ),
    ]
