# Generated by Django 3.1.5 on 2021-03-14 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interflowApp', '0005_auto_20210314_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='file',
        ),
    ]
