# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(600, 375)
        Login.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Login.setStyleSheet("background-image: url(:/pic/bg.png);")
        self.tabWidget = QtWidgets.QTabWidget(Login)
        self.tabWidget.setGeometry(QtCore.QRect(10, 70, 181, 201))
        self.tabWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 151, 111))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.userName = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.userName.setFont(font)
        self.userName.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.userName.setText("")
        self.userName.setObjectName("userName")
        self.gridLayout.addWidget(self.userName, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.password = QtWidgets.QLineEdit(self.layoutWidget)
        self.password.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.gridLayout.addWidget(self.password, 1, 1, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 140, 158, 25))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.login_btn = QtWidgets.QPushButton(self.layoutWidget1)
        self.login_btn.setObjectName("login_btn")
        self.horizontalLayout.addWidget(self.login_btn)
        self.to_register = QtWidgets.QPushButton(self.layoutWidget1)
        self.to_register.setObjectName("to_register")
        self.horizontalLayout.addWidget(self.to_register)
        self.tabWidget.addTab(self.tab, "")
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.layoutWidget_3 = QtWidgets.QWidget(self.widget)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 10, 151, 111))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.Admin = QtWidgets.QLineEdit(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Admin.setFont(font)
        self.Admin.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.Admin.setText("")
        self.Admin.setObjectName("Admin")
        self.gridLayout_2.addWidget(self.Admin, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.admin_password = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.admin_password.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.admin_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.admin_password.setObjectName("admin_password")
        self.gridLayout_2.addWidget(self.admin_password, 1, 1, 1, 1)
        self.layoutWidget_2 = QtWidgets.QWidget(self.widget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 140, 158, 25))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.login_admin = QtWidgets.QPushButton(self.layoutWidget_2)
        self.login_admin.setObjectName("login_admin")
        self.horizontalLayout_2.addWidget(self.login_admin)
        self.register_amin = QtWidgets.QPushButton(self.layoutWidget_2)
        self.register_amin.setObjectName("register_amin")
        self.horizontalLayout_2.addWidget(self.register_amin)
        self.tabWidget.addTab(self.widget, "")

        self.retranslateUi(Login)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "登录界面"))
        self.label_2.setText(_translate("Login", "用户名"))
        self.label_3.setText(_translate("Login", "密码"))
        self.login_btn.setText(_translate("Login", "登陆"))
        self.to_register.setText(_translate("Login", "注册"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Login", "用户"))
        self.label_4.setText(_translate("Login", "管理员"))
        self.label_5.setText(_translate("Login", "密码"))
        self.login_admin.setText(_translate("Login", "登陆"))
        self.register_amin.setText(_translate("Login", "注册"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), _translate("Login", "管理员"))


import source.apprcc_rc
