# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'table.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Table(object):
    def setupUi(self, Table):
        Table.setObjectName("Table")
        Table.resize(704, 625)
        self.btn_1 = QtWidgets.QPushButton(Table)
        self.btn_1.setGeometry(QtCore.QRect(50, 30, 80, 80))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_1.setFont(font)
        self.btn_1.setStyleSheet("border-radius: 40px;  border: 2px groove gray;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.btn_1.setObjectName("btn_1")
        self.btn_2 = QtWidgets.QPushButton(Table)
        self.btn_2.setGeometry(QtCore.QRect(150, 30, 80, 80))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_2.setFont(font)
        self.btn_2.setStyleSheet("border-radius: 40px;  border: 2px groove gray;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.btn_2.setObjectName("btn_2")
        self.btn_5 = QtWidgets.QPushButton(Table)
        self.btn_5.setGeometry(QtCore.QRect(450, 30, 80, 80))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_5.setFont(font)
        self.btn_5.setStyleSheet("border-radius: 40px;  border: 2px groove gray;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.btn_5.setObjectName("btn_5")
        self.btn_6 = QtWidgets.QPushButton(Table)
        self.btn_6.setGeometry(QtCore.QRect(550, 30, 80, 80))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_6.setFont(font)
        self.btn_6.setStyleSheet("border-radius: 40px;  border: 2px groove gray;\n"
"background-color: rgb(255, 255, 255);")
        self.btn_6.setObjectName("btn_6")
        self.btn_7 = QtWidgets.QPushButton(Table)
        self.btn_7.setGeometry(QtCore.QRect(50, 180, 80, 80))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_7.setFont(font)
        self.btn_7.setStyleSheet("border-radius: 40px;  border: 2px groove gray;\n"
"background-color: rgb(255, 255, 255);")
        self.btn_7.setObjectName("btn_7")
        self.btn_8 = QtWidgets.QPushButton(Table)
        self.btn_8.setGeometry(QtCore.QRect(150, 180, 80, 80))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_8.setFont(font)
        self.btn_8.setStyleSheet("border-radius: 40px;  border: 2px groove gray;\n"
"background-color: rgb(255, 255, 255);")
        self.btn_8.setObjectName("btn_8")
        self.label = QtWidgets.QLabel(Table)
        self.label.setGeometry(QtCore.QRect(300, 110, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.btn_9 = QtWidgets.QPushButton(Table)
        self.btn_9.setGeometry(QtCore.QRect(250, 180, 80, 80))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_9.setFont(font)
        self.btn_9.setStyleSheet("border-radius: 40px;  border: 2px groove gray;background-color: rgb(255, 255, 255);")
        self.btn_9.setObjectName("btn_9")
        self.btn_10 = QtWidgets.QPushButton(Table)
        self.btn_10.setGeometry(QtCore.QRect(350, 180, 80, 80))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_10.setFont(font)
        self.btn_10.setStyleSheet("border-radius: 40px;  border: 2px groove gray;\n"
"background-color: rgb(255, 255, 255);")
        self.btn_10.setObjectName("btn_10")
        self.btn_11 = QtWidgets.QPushButton(Table)
        self.btn_11.setGeometry(QtCore.QRect(450, 180, 80, 80))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_11.setFont(font)
        self.btn_11.setStyleSheet("border-radius: 40px;  border: 2px groove gray;\n"
"background-color: rgb(255, 255, 255);")
        self.btn_11.setObjectName("btn_11")
        self.btn_12 = QtWidgets.QPushButton(Table)
        self.btn_12.setGeometry(QtCore.QRect(550, 180, 80, 80))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_12.setFont(font)
        self.btn_12.setStyleSheet("border-radius: 40px;  border: 2px groove gray;background-color: rgb(255, 255, 255);")
        self.btn_12.setObjectName("btn_12")
        self.btn_13 = QtWidgets.QPushButton(Table)
        self.btn_13.setGeometry(QtCore.QRect(50, 330, 80, 80))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_13.setFont(font)
        self.btn_13.setStyleSheet("border-radius: 40px;  border: 2px groove gray;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.btn_13.setObjectName("btn_13")
        self.label_2 = QtWidgets.QLabel(Table)
        self.label_2.setGeometry(QtCore.QRect(300, 260, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.btn_14 = QtWidgets.QPushButton(Table)
        self.btn_14.setGeometry(QtCore.QRect(150, 330, 80, 80))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_14.setFont(font)
        self.btn_14.setStyleSheet("border-radius: 40px;  border: 2px groove gray;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.btn_14.setObjectName("btn_14")
        self.btn_15 = QtWidgets.QPushButton(Table)
        self.btn_15.setGeometry(QtCore.QRect(250, 330, 80, 80))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_15.setFont(font)
        self.btn_15.setStyleSheet("border-radius: 40px;  border: 2px groove gray;\n"
"background-color: rgb(255, 255, 255);")
        self.btn_15.setObjectName("btn_15")
        self.btn_16 = QtWidgets.QPushButton(Table)
        self.btn_16.setGeometry(QtCore.QRect(350, 330, 80, 80))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_16.setFont(font)
        self.btn_16.setStyleSheet("border-radius: 40px;  border: 2px groove gray;\n"
"background-color: rgb(255, 255, 255);")
        self.btn_16.setObjectName("btn_16")
        self.btn_20 = QtWidgets.QPushButton(Table)
        self.btn_20.setGeometry(QtCore.QRect(150, 480, 80, 80))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_20.setFont(font)
        self.btn_20.setStyleSheet("border-radius: 40px;  border: 2px groove gray;\n"
"")
        self.btn_20.setObjectName("btn_20")
        self.btn_18 = QtWidgets.QPushButton(Table)
        self.btn_18.setGeometry(QtCore.QRect(550, 330, 80, 80))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_18.setFont(font)
        self.btn_18.setStyleSheet("border-radius: 40px;  border: 2px groove gray;\n"
"background-color: rgb(255, 255, 255);")
        self.btn_18.setObjectName("btn_18")
        self.label_3 = QtWidgets.QLabel(Table)
        self.label_3.setGeometry(QtCore.QRect(300, 410, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.btn_19 = QtWidgets.QPushButton(Table)
        self.btn_19.setGeometry(QtCore.QRect(50, 480, 80, 80))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_19.setFont(font)
        self.btn_19.setStyleSheet("border-radius: 40px;  border: 2px groove gray;\n"
"")
        self.btn_19.setObjectName("btn_19")
        self.btn_22 = QtWidgets.QPushButton(Table)
        self.btn_22.setGeometry(QtCore.QRect(350, 480, 80, 80))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_22.setFont(font)
        self.btn_22.setStyleSheet("border-radius: 40px;  border: 2px groove gray;\n"
"")
        self.btn_22.setObjectName("btn_22")
        self.btn_23 = QtWidgets.QPushButton(Table)
        self.btn_23.setGeometry(QtCore.QRect(450, 480, 80, 80))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_23.setFont(font)
        self.btn_23.setStyleSheet("border-radius: 40px;  border: 2px groove gray;\n"
"")
        self.btn_23.setObjectName("btn_23")
        self.btn_21 = QtWidgets.QPushButton(Table)
        self.btn_21.setGeometry(QtCore.QRect(250, 480, 80, 80))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_21.setFont(font)
        self.btn_21.setStyleSheet("border-radius: 40px;  border: 2px groove gray;\n"
"")
        self.btn_21.setObjectName("btn_21")
        self.btn_24 = QtWidgets.QPushButton(Table)
        self.btn_24.setGeometry(QtCore.QRect(550, 480, 80, 80))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_24.setFont(font)
        self.btn_24.setStyleSheet("border-radius: 40px;  border: 2px groove gray;\n"
"")
        self.btn_24.setObjectName("btn_24")
        self.btn_17 = QtWidgets.QPushButton(Table)
        self.btn_17.setGeometry(QtCore.QRect(450, 330, 80, 80))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_17.setFont(font)
        self.btn_17.setStyleSheet("border-radius: 40px;  border: 2px groove gray;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.btn_17.setObjectName("btn_17")
        self.btn_3 = QtWidgets.QPushButton(Table)
        self.btn_3.setGeometry(QtCore.QRect(250, 30, 80, 80))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_3.setFont(font)
        self.btn_3.setStyleSheet("border-radius: 40px;  border: 2px groove gray;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.btn_3.setObjectName("btn_3")
        self.btn_4 = QtWidgets.QPushButton(Table)
        self.btn_4.setGeometry(QtCore.QRect(350, 30, 80, 80))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_4.setFont(font)
        self.btn_4.setStyleSheet("border-radius: 40px;  border: 2px groove gray;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.btn_4.setObjectName("btn_4")
        self.label_4 = QtWidgets.QLabel(Table)
        self.label_4.setGeometry(QtCore.QRect(300, 560, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Table)
        QtCore.QMetaObject.connectSlotsByName(Table)

    def retranslateUi(self, Table):
        _translate = QtCore.QCoreApplication.translate
        Table.setWindowTitle(_translate("Table", "餐桌界面"))
        self.btn_1.setText(_translate("Table", "1号桌"))
        self.btn_2.setText(_translate("Table", "2号桌"))
        self.btn_5.setText(_translate("Table", "5号桌"))
        self.btn_6.setText(_translate("Table", "6号桌"))
        self.btn_7.setText(_translate("Table", "7号桌"))
        self.btn_8.setText(_translate("Table", "8号桌"))
        self.label.setText(_translate("Table", "1-6号桌为2人座"))
        self.btn_9.setText(_translate("Table", "9号桌"))
        self.btn_10.setText(_translate("Table", "10号桌"))
        self.btn_11.setText(_translate("Table", "11号桌"))
        self.btn_12.setText(_translate("Table", "12号桌"))
        self.btn_13.setText(_translate("Table", "13号桌"))
        self.label_2.setText(_translate("Table", "7-12号桌为4人座"))
        self.btn_14.setText(_translate("Table", "14号桌"))
        self.btn_15.setText(_translate("Table", "15号桌"))
        self.btn_16.setText(_translate("Table", "16号桌"))
        self.btn_20.setText(_translate("Table", "20号桌"))
        self.btn_18.setText(_translate("Table", "18号桌"))
        self.label_3.setText(_translate("Table", "13-18号桌为6人座"))
        self.btn_19.setText(_translate("Table", "19号桌"))
        self.btn_22.setText(_translate("Table", "22号桌"))
        self.btn_23.setText(_translate("Table", "23号桌"))
        self.btn_21.setText(_translate("Table", "21号桌"))
        self.btn_24.setText(_translate("Table", "24号桌"))
        self.btn_17.setText(_translate("Table", "17号桌"))
        self.btn_3.setText(_translate("Table", "3号桌"))
        self.btn_4.setText(_translate("Table", "4号桌"))
        self.label_4.setText(_translate("Table", "19-24号桌为8人座"))


