# Generated by Django 3.1.5 on 2021-03-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='标题')),
                ('introduce', models.CharField(blank=True, max_length=200, verbose_name='描述')),
                ('photo', models.ImageField(blank=True, upload_to='images/album/', verbose_name='图片')),
            ],
            options={
                'verbose_name': '图片墙管理',
                'verbose_name_plural': '图片墙管理',
            },
        ),
    ]
