# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'General.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_General(object):
    def setupUi(self, General):
        General.setObjectName("General")
        General.resize(737, 608)
        self.verticalLayout = QtWidgets.QVBoxLayout(General)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.math = QtWidgets.QPushButton(General)
        self.math.setObjectName("math")
        self.horizontalLayout.addWidget(self.math)
        self.chinese = QtWidgets.QPushButton(General)
        self.chinese.setObjectName("chinese")
        self.horizontalLayout.addWidget(self.chinese)
        self.english = QtWidgets.QPushButton(General)
        self.english.setObjectName("english")
        self.horizontalLayout.addWidget(self.english)
        self.physics = QtWidgets.QPushButton(General)
        self.physics.setObjectName("physics")
        self.horizontalLayout.addWidget(self.physics)
        self.chemistry = QtWidgets.QPushButton(General)
        self.chemistry.setObjectName("chemistry")
        self.horizontalLayout.addWidget(self.chemistry)
        self.biology = QtWidgets.QPushButton(General)
        self.biology.setObjectName("biology")
        self.horizontalLayout.addWidget(self.biology)
        self.science = QtWidgets.QPushButton(General)
        self.science.setObjectName("science")
        self.horizontalLayout.addWidget(self.science)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(General)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(General)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(General)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(General)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 3, 1, 1)
        self.label = QtWidgets.QLabel(General)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(General)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 5, 1, 1)
        self.Max = QtWidgets.QLCDNumber(General)
        self.Max.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.Max.setObjectName("Max")
        self.gridLayout.addWidget(self.Max, 1, 0, 1, 1)
        self.Min = QtWidgets.QLCDNumber(General)
        self.Min.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.Min.setObjectName("Min")
        self.gridLayout.addWidget(self.Min, 1, 1, 1, 1)
        self.Avg = QtWidgets.QLCDNumber(General)
        self.Avg.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.Avg.setObjectName("Avg")
        self.gridLayout.addWidget(self.Avg, 1, 2, 1, 1)
        self.Std = QtWidgets.QLCDNumber(General)
        self.Std.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.Std.setObjectName("Std")
        self.gridLayout.addWidget(self.Std, 1, 3, 1, 1)
        self.Mid = QtWidgets.QLCDNumber(General)
        self.Mid.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.Mid.setObjectName("Mid")
        self.gridLayout.addWidget(self.Mid, 1, 4, 1, 1)
        self.Dif = QtWidgets.QLCDNumber(General)
        self.Dif.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.Dif.setObjectName("Dif")
        self.gridLayout.addWidget(self.Dif, 1, 5, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.tabWidget = QtWidgets.QTabWidget(General)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.webEngineView = QtWebEngineWidgets.QWebEngineView(self.tab)
        self.webEngineView.setUrl(QtCore.QUrl("about:blank"))
        self.webEngineView.setObjectName("webEngineView")
        self.horizontalLayout_2.addWidget(self.webEngineView)
        self.tabWidget.addTab(self.tab, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(General)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(General)

    def retranslateUi(self, General):
        _translate = QtCore.QCoreApplication.translate
        General.setWindowTitle(_translate("General", "学生成绩概括界面"))
        self.math.setText(_translate("General", "数学"))
        self.chinese.setText(_translate("General", "语文"))
        self.english.setText(_translate("General", "英语"))
        self.physics.setText(_translate("General", "物理"))
        self.chemistry.setText(_translate("General", "化学"))
        self.biology.setText(_translate("General", "生物"))
        self.science.setText(_translate("General", "理综"))
        self.label_5.setText(_translate("General", "最高分"))
        self.label_4.setText(_translate("General", "最低分"))
        self.label_6.setText(_translate("General", "平均分"))
        self.label_2.setText(_translate("General", "标准差"))
        self.label.setText(_translate("General", "中位数"))
        self.label_3.setText(_translate("General", "差异系数"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("General", "图像"))


from PyQt5 import QtWebEngineWidgets
