# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Math.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Math(object):
    def setupUi(self, Math):
        Math.setObjectName("Math")
        Math.resize(696, 606)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(Math)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Math)
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(Math)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_4 = QtWidgets.QLabel(Math)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(Math)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.Export_btn = QtWidgets.QPushButton(Math)
        self.Export_btn.setObjectName("Export_btn")
        self.horizontalLayout.addWidget(self.Export_btn)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.tabWidget = QtWidgets.QTabWidget(Math)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 5, 1, 1)
        self.Min = QtWidgets.QLCDNumber(self.tab)
        self.Min.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.Min.setObjectName("Min")
        self.gridLayout.addWidget(self.Min, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 1, 1, 1)
        self.Max = QtWidgets.QLCDNumber(self.tab)
        self.Max.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.Max.setObjectName("Max")
        self.gridLayout.addWidget(self.Max, 2, 0, 1, 1)
        self.Std = QtWidgets.QLCDNumber(self.tab)
        self.Std.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.Std.setObjectName("Std")
        self.gridLayout.addWidget(self.Std, 2, 3, 1, 1)
        self.Dif = QtWidgets.QLCDNumber(self.tab)
        self.Dif.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.Dif.setObjectName("Dif")
        self.gridLayout.addWidget(self.Dif, 2, 5, 1, 1)
        self.Mid = QtWidgets.QLCDNumber(self.tab)
        self.Mid.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.Mid.setObjectName("Mid")
        self.gridLayout.addWidget(self.Mid, 2, 4, 1, 1)
        self.Avg = QtWidgets.QLCDNumber(self.tab)
        self.Avg.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.Avg.setObjectName("Avg")
        self.gridLayout.addWidget(self.Avg, 2, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.tabWidget11 = QtWidgets.QTabWidget(self.tab)
        self.tabWidget11.setObjectName("tabWidget11")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.webEngineView11 = QtWebEngineWidgets.QWebEngineView(self.tab_5)
        self.webEngineView11.setUrl(QtCore.QUrl("about:blank"))
        self.webEngineView11.setObjectName("webEngineView11")
        self.horizontalLayout_2.addWidget(self.webEngineView11)
        self.tabWidget11.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.webEngineView12 = QtWebEngineWidgets.QWebEngineView(self.tab_6)
        self.webEngineView12.setUrl(QtCore.QUrl("about:blank"))
        self.webEngineView12.setObjectName("webEngineView12")
        self.horizontalLayout_3.addWidget(self.webEngineView12)
        self.tabWidget11.addTab(self.tab_6, "")
        self.verticalLayout.addWidget(self.tabWidget11)
        self.tabWidget_3 = QtWidgets.QTabWidget(self.tab)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab_7)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.report1 = QtWidgets.QTextEdit(self.tab_7)
        self.report1.setObjectName("report1")
        self.horizontalLayout_4.addWidget(self.report1)
        self.tabWidget_3.addTab(self.tab_7, "")
        self.verticalLayout.addWidget(self.tabWidget_3)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter = QtWidgets.QSplitter(self.tab_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label_11 = QtWidgets.QLabel(self.splitter)
        self.label_11.setObjectName("label_11")
        self.Max_2 = QtWidgets.QLineEdit(self.splitter)
        self.Max_2.setObjectName("Max_2")
        self.label_12 = QtWidgets.QLabel(self.splitter)
        self.label_12.setObjectName("label_12")
        self.Min_2 = QtWidgets.QLineEdit(self.splitter)
        self.Min_2.setObjectName("Min_2")
        self.label_13 = QtWidgets.QLabel(self.splitter)
        self.label_13.setObjectName("label_13")
        self.distance = QtWidgets.QLineEdit(self.splitter)
        self.distance.setText("")
        self.distance.setObjectName("distance")
        self.fresh = QtWidgets.QPushButton(self.splitter)
        self.fresh.setObjectName("fresh")
        self.draw = QtWidgets.QPushButton(self.splitter)
        self.draw.setObjectName("draw")
        self.verticalLayout_2.addWidget(self.splitter)
        self.tabWidget21 = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget21.setObjectName("tabWidget21")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tab_8)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.webEngineView21 = QtWebEngineWidgets.QWebEngineView(self.tab_8)
        self.webEngineView21.setUrl(QtCore.QUrl("about:blank"))
        self.webEngineView21.setObjectName("webEngineView21")
        self.horizontalLayout_5.addWidget(self.webEngineView21)
        self.tabWidget21.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.tab_9)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.webEngineView22 = QtWebEngineWidgets.QWebEngineView(self.tab_9)
        self.webEngineView22.setUrl(QtCore.QUrl("about:blank"))
        self.webEngineView22.setObjectName("webEngineView22")
        self.horizontalLayout_6.addWidget(self.webEngineView22)
        self.tabWidget21.addTab(self.tab_9, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.tab_11)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.webEngineView23 = QtWebEngineWidgets.QWebEngineView(self.tab_11)
        self.webEngineView23.setUrl(QtCore.QUrl("about:blank"))
        self.webEngineView23.setObjectName("webEngineView23")
        self.horizontalLayout_8.addWidget(self.webEngineView23)
        self.tabWidget21.addTab(self.tab_11, "")
        self.verticalLayout_2.addWidget(self.tabWidget21)
        self.tabWidget_5 = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget_5.setObjectName("tabWidget_5")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.tab_10)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.report2 = QtWidgets.QTextEdit(self.tab_10)
        self.report2.setObjectName("report2")
        self.horizontalLayout_7.addWidget(self.report2)
        self.tabWidget_5.addTab(self.tab_10, "")
        self.verticalLayout_2.addWidget(self.tabWidget_5)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_14 = QtWidgets.QLabel(self.tab_3)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_9.addWidget(self.label_14)
        self.excellent = QtWidgets.QLCDNumber(self.tab_3)
        self.excellent.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.excellent.setProperty("value", 0.0)
        self.excellent.setObjectName("excellent")
        self.horizontalLayout_9.addWidget(self.excellent)
        self.label_15 = QtWidgets.QLabel(self.tab_3)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_9.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(self.tab_3)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_9.addWidget(self.label_16)
        self.fine = QtWidgets.QLCDNumber(self.tab_3)
        self.fine.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.fine.setObjectName("fine")
        self.horizontalLayout_9.addWidget(self.fine)
        self.label_17 = QtWidgets.QLabel(self.tab_3)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_9.addWidget(self.label_17)
        self.label_18 = QtWidgets.QLabel(self.tab_3)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_9.addWidget(self.label_18)
        self.Pass = QtWidgets.QLCDNumber(self.tab_3)
        self.Pass.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.Pass.setObjectName("Pass")
        self.horizontalLayout_9.addWidget(self.Pass)
        self.label_19 = QtWidgets.QLabel(self.tab_3)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_9.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(self.tab_3)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_9.addWidget(self.label_20)
        self.low = QtWidgets.QLCDNumber(self.tab_3)
        self.low.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.low.setObjectName("low")
        self.horizontalLayout_9.addWidget(self.low)
        self.label_21 = QtWidgets.QLabel(self.tab_3)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_9.addWidget(self.label_21)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.tabWidget31 = QtWidgets.QTabWidget(self.tab_3)
        self.tabWidget31.setObjectName("tabWidget31")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.tab_12)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.webEngineView31 = QtWebEngineWidgets.QWebEngineView(self.tab_12)
        self.webEngineView31.setUrl(QtCore.QUrl("about:blank"))
        self.webEngineView31.setObjectName("webEngineView31")
        self.horizontalLayout_10.addWidget(self.webEngineView31)
        self.tabWidget31.addTab(self.tab_12, "")
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.tab_13)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.webEngineView32 = QtWebEngineWidgets.QWebEngineView(self.tab_13)
        self.webEngineView32.setUrl(QtCore.QUrl("about:blank"))
        self.webEngineView32.setObjectName("webEngineView32")
        self.horizontalLayout_11.addWidget(self.webEngineView32)
        self.tabWidget31.addTab(self.tab_13, "")
        self.verticalLayout_3.addWidget(self.tabWidget31)
        self.tabWidget_7 = QtWidgets.QTabWidget(self.tab_3)
        self.tabWidget_7.setObjectName("tabWidget_7")
        self.tab_14 = QtWidgets.QWidget()
        self.tab_14.setObjectName("tab_14")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.tab_14)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.report3 = QtWidgets.QTextEdit(self.tab_14)
        self.report3.setObjectName("report3")
        self.horizontalLayout_12.addWidget(self.report3)
        self.tabWidget_7.addTab(self.tab_14, "")
        self.verticalLayout_3.addWidget(self.tabWidget_7)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_25 = QtWidgets.QLabel(self.tab_4)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_15.addWidget(self.label_25)
        self.one_2 = QtWidgets.QLineEdit(self.tab_4)
        self.one_2.setObjectName("one_2")
        self.horizontalLayout_15.addWidget(self.one_2)
        self.label_26 = QtWidgets.QLabel(self.tab_4)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_15.addWidget(self.label_26)
        self.two_2 = QtWidgets.QLineEdit(self.tab_4)
        self.two_2.setObjectName("two_2")
        self.horizontalLayout_15.addWidget(self.two_2)
        self.label_27 = QtWidgets.QLabel(self.tab_4)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_15.addWidget(self.label_27)
        self.three_2 = QtWidgets.QLineEdit(self.tab_4)
        self.three_2.setObjectName("three_2")
        self.horizontalLayout_15.addWidget(self.three_2)
        self.clear_3 = QtWidgets.QPushButton(self.tab_4)
        self.clear_3.setObjectName("clear_3")
        self.horizontalLayout_15.addWidget(self.clear_3)
        self.draw_4 = QtWidgets.QPushButton(self.tab_4)
        self.draw_4.setObjectName("draw_4")
        self.horizontalLayout_15.addWidget(self.draw_4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_15)
        self.tabWidget41 = QtWidgets.QTabWidget(self.tab_4)
        self.tabWidget41.setObjectName("tabWidget41")
        self.tab_15 = QtWidgets.QWidget()
        self.tab_15.setObjectName("tab_15")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.tab_15)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.webEngineView41 = QtWebEngineWidgets.QWebEngineView(self.tab_15)
        self.webEngineView41.setUrl(QtCore.QUrl("about:blank"))
        self.webEngineView41.setObjectName("webEngineView41")
        self.horizontalLayout_16.addWidget(self.webEngineView41)
        self.tabWidget41.addTab(self.tab_15, "")
        self.tab_17 = QtWidgets.QWidget()
        self.tab_17.setObjectName("tab_17")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.tab_17)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.webEngineView42 = QtWebEngineWidgets.QWebEngineView(self.tab_17)
        self.webEngineView42.setUrl(QtCore.QUrl("about:blank"))
        self.webEngineView42.setObjectName("webEngineView42")
        self.horizontalLayout_13.addWidget(self.webEngineView42)
        self.tabWidget41.addTab(self.tab_17, "")
        self.tab_18 = QtWidgets.QWidget()
        self.tab_18.setObjectName("tab_18")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.tab_18)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.webEngineView43 = QtWebEngineWidgets.QWebEngineView(self.tab_18)
        self.webEngineView43.setUrl(QtCore.QUrl("about:blank"))
        self.webEngineView43.setObjectName("webEngineView43")
        self.horizontalLayout_17.addWidget(self.webEngineView43)
        self.tabWidget41.addTab(self.tab_18, "")
        self.verticalLayout_4.addWidget(self.tabWidget41)
        self.tabWidget_9 = QtWidgets.QTabWidget(self.tab_4)
        self.tabWidget_9.setObjectName("tabWidget_9")
        self.tab_16 = QtWidgets.QWidget()
        self.tab_16.setObjectName("tab_16")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.tab_16)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.report4 = QtWidgets.QTextEdit(self.tab_16)
        self.report4.setObjectName("report4")
        self.horizontalLayout_14.addWidget(self.report4)
        self.tabWidget_9.addTab(self.tab_16, "")
        self.verticalLayout_4.addWidget(self.tabWidget_9)
        self.tabWidget.addTab(self.tab_4, "")
        self.verticalLayout_5.addWidget(self.tabWidget)

        self.retranslateUi(Math)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget11.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        self.tabWidget21.setCurrentIndex(0)
        self.tabWidget_5.setCurrentIndex(0)
        self.tabWidget31.setCurrentIndex(0)
        self.tabWidget_7.setCurrentIndex(0)
        self.tabWidget41.setCurrentIndex(0)
        self.tabWidget_9.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Math)

    def retranslateUi(self, Math):
        _translate = QtCore.QCoreApplication.translate
        Math.setWindowTitle(_translate("Math", "Form"))
        self.Export_btn.setText(_translate("Math", "输出为文档"))
        self.label_10.setText(_translate("Math", "差异系数"))
        self.label_5.setText(_translate("Math", "最高分"))
        self.label_9.setText(_translate("Math", "中位数"))
        self.label_7.setText(_translate("Math", "平均分"))
        self.label_6.setText(_translate("Math", "最低分"))
        self.label_8.setText(_translate("Math", "标准差"))
        self.tabWidget11.setTabText(self.tabWidget11.indexOf(self.tab_5), _translate("Math", "面积图"))
        self.tabWidget11.setTabText(self.tabWidget11.indexOf(self.tab_6), _translate("Math", "饼图"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_7), _translate("Math", "分析"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Math", "成绩概括"))
        self.label_11.setText(_translate("Math", "最高分"))
        self.label_12.setText(_translate("Math", "最低分"))
        self.label_13.setText(_translate("Math", "分段间隔"))
        self.fresh.setText(_translate("Math", "重置"))
        self.draw.setText(_translate("Math", "确定"))
        self.tabWidget21.setTabText(self.tabWidget21.indexOf(self.tab_8), _translate("Math", "直方图"))
        self.tabWidget21.setTabText(self.tabWidget21.indexOf(self.tab_9), _translate("Math", "饼图"))
        self.tabWidget21.setTabText(self.tabWidget21.indexOf(self.tab_11), _translate("Math", "表"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_10), _translate("Math", "分析"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Math", "分段成绩"))
        self.label_14.setText(_translate("Math", "优秀率"))
        self.label_15.setText(_translate("Math", "%"))
        self.label_16.setText(_translate("Math", "良好率"))
        self.label_17.setText(_translate("Math", "%"))
        self.label_18.setText(_translate("Math", "及格率"))
        self.label_19.setText(_translate("Math", "%"))
        self.label_20.setText(_translate("Math", "低分率"))
        self.label_21.setText(_translate("Math", "%"))
        self.tabWidget31.setTabText(self.tabWidget31.indexOf(self.tab_12), _translate("Math", "平均分"))
        self.tabWidget31.setTabText(self.tabWidget31.indexOf(self.tab_13), _translate("Math", "四率图"))
        self.tabWidget_7.setTabText(self.tabWidget_7.indexOf(self.tab_14), _translate("Math", "分析"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Math", "四率一分"))
        self.label_25.setText(_translate("Math", "一档线"))
        self.label_26.setText(_translate("Math", "二档线"))
        self.label_27.setText(_translate("Math", "三档线"))
        self.clear_3.setText(_translate("Math", "重置"))
        self.draw_4.setText(_translate("Math", "确定"))
        self.tabWidget41.setTabText(self.tabWidget41.indexOf(self.tab_15), _translate("Math", "表格"))
        self.tabWidget41.setTabText(self.tabWidget41.indexOf(self.tab_17), _translate("Math", "一档图"))
        self.tabWidget41.setTabText(self.tabWidget41.indexOf(self.tab_18), _translate("Math", "二档图"))
        self.tabWidget_9.setTabText(self.tabWidget_9.indexOf(self.tab_16), _translate("Math", "分析"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Math", "分档成绩"))


from PyQt5 import QtWebEngineWidgets
