"""
Django settings for myblog project.

Generated by 'django-admin startproject' using Django 3.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'f^^^p-j@*tho)wdkw92+8-2*&^@1#!bquulkt4+$=!f8ll(8t6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'home',
    'userApp',
    'interflowApp',
    'photoApp',
    'articleApp',
    'DjangoUeditor',
    'widget_tweaks',
    #添加验证码功能
    'captcha',
    'haystack',
]

MIDDLEWARE= [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    #添加中间件LocaleMiddleware
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myblog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myblog.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'blogdb',
        'USER':'yxg',
        'PASSWORD':'yxg579521..',
        'HOST':'127.0.0.1',
        'PORT':'3306',
    },
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'#设置语言为中文

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS=[
    os.path.join(BASE_DIR,'static'),
]
MEDIA_URL='/media/'
MEDIA_ROOT=os.path.join(BASE_DIR,'media/')
AUTH_USER_MODEL = "userApp.MyUser"

HAYSTACK_CONNECTIONS={
    'default':{
        'ENGINE':'articleApp.whoosh_backend.WhooshEngine',
        'PATH':os.path.join(BASE_DIR,'whoosh_index'),
    },
}
HAYSTACK_SEARCH_RESULTS_PER_PAGE=6
HAYSTACK_SIGNAL_PROCESSOR='haystack.signals.RealtimeSignalProcessor'

EMAIL_HOST='smtp.qq.com'
EMAIL_POST=25
EMAIL_HOST_USER='2931148038@qq.com'
EMAIL_HOST_PASSWORD='jahvzuqrryfoddbi'
EMAIL_USE_TLS=True

CAPTCHA_NOISE_FUNCTIONS=(
    #设置样式
    'captcha.helpers.noise_null',
    #设置干扰线
    'captcha.helpers.noise_arcs',
    #设置干扰点
    'captcha.helpers.noise_dots',)
#设置图片大小
CAPTCHA_IMAGE_SIZE=(100,25)
#设置图片背景颜色
CAPTCHA_BACKGROUND_COLOR='#ffffff'
#图片文字为随机英文字母
CAPTCHA_CHALLENGE_FUNCT='captcha.helpers.random_char_challenge'
#图片文字为英文单词
CAPTCHA_CHALLENGE_FUNCT='captcha.helpers.word_challenge'
#图片文字为数字表达式
CAPTCHA_CHALLENGE_FUNCT='captcha.helpers.math_challenge'
#设置字符个数
CAPTCHA_LENGTH=4
#设置超时(minutes)
CAPTCHA_TIMEOUT=1