# Generated by Django 3.1.5 on 2021-03-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(default='用户不选择公开邮箱', max_length=50, verbose_name='邮箱'),
        ),
    ]
