# Generated by Django 3.1.5 on 2021-03-09 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleApp', '0002_auto_20210309_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_post',
            name='user',
        ),
    ]
