# Generated by Django 3.1.5 on 2021-03-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleApp', '0004_blog_post_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
