# Generated by Django 3.1.5 on 2021-03-21 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleApp', '0005_auto_20210310_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentator',
            field=models.CharField(max_length=50, verbose_name='匿名用户'),
        ),
    ]
